[test]
# To require 50% line-level and function-level coverage
# Don't cover too much, we're not keeping code,
# we're keeping behavior and expectations.
# Tests should survive refactoring.
coverageThreshold = 0.5
